name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Remove PR preview directory
      run: |
        PR_DIR="pr/${{ github.event.number }}"
        if [ -d "$PR_DIR" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git rm -rf "$PR_DIR"
          git commit -m "Remove preview for PR #${{ github.event.number }}"
          git push origin gh-pages
          echo "✅ Removed preview directory: $PR_DIR"
        else
          echo "⚠️ Preview directory not found: $PR_DIR"
        fi